### ISSUE TITLE
ERROR while ng build --prod "Cannot negate a statement"

### ISSUE THREAD

**Issue by chvishwakarma** [terser/terser#1037]
./node_modules/.bin/ng build --prod --base-href /project

ERROR in main-es2015.110a0182c67c95b8de43.js from Terser
Error: Cannot negate a statement
    at AST_ClassExpression.<anonymous> (/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:175355)
    at AST_ClassExpression.negate (/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:176467)
    at /node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:200508
    at AST_If.optimize (/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:137605)
    at ai.before (/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:137382)
    at AST_If.transform (/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:84306)
    at /node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:84470
    at l (/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:953)
    at e (/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:1273)
    at kn (/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:84444)

**Versions :** 

 "terser": "4.6.3",
 "terser-webpack-plugin": "3.0.3",
 "webpack": "4.39.2",
 "@angular-devkit/architect": "0.803.29",
 "@angular-devkit/build-optimizer": "0.803.29",
 "@angular-devkit/build-webpack": "0.803.29",
 "@angular-devkit/core": "8.3.29",

**Comment by fabiosantoscode** [comment]
Hello there! Two things:

 - Can you provide a small reproduction for this issue, with the input code?
 - Can you try the latest version of Terser?

**Comment by chvishwakarma** [comment]
I am not sure where in code it's throwing error it's huge code base. I tried with latest version of Terser still facing same issue. If I use uglify-js plugin with @angular-builders/custom-webpack it's able to minify the bundles. So I am trying to migrate my angular project from 8.1 to 10. Can you suggest me how can I find the where in source code it's breaking ? Also I don't get what "Error: Cannot negate a statement" means ?

**Comment by fabiosantoscode** [comment]
"cannot negate a statement" occurs when terser is trying to do something like turning `!(a === b)` into `a !== b` to save space.

However a statement like return or if is being passed to it accidentally. It's really hard to understand what failed without knowing what code triggered it.

To create a minimal repro, you can remove things from your application until the error no longer occurs. Binary search is also possible (eg remove an entire folder and check, if the error disappeared it must be in that folder).

Now that I think of it, though, the best option here would be to print out nearby code in these error messages.

**Comment by chvishwakarma** [comment]
Thanks for explaining it. let me try Binary search way and get back. I will also try putting logs in terser plugin as suggested. Can you suggest where should I put these logs inside terser plugin ?

**Comment by fabiosantoscode** [comment]
I'm the one who needs to set this up :)

But it would be on Terser 5

I do want to insist that you try this out with Terser 5 if you can. It's the version that's being actively developed right now. I know it can be hard since terser is a transitive dependency, but it might just fix your bug. And if you're in the middle of a migration, you can always turn it off until you're finished and able to use Terser 5

**Comment by jridgewell** [comment]
@chvishwakarma: Were you able to track this down? If not, you could try modifying the terser code in your node_modules with something like this:

```js
// Add this before the `throw` statement in terser
console.trace(this.print_to_string());
throw new Error("Cannot negate a statement");
```

That should track down the class that's causing an issue. We'll need that and the surrounding code to figure out what's going on.
