### ISSUE TITLE
Error in Ruby on Rails 7.0.3 with terser compressor

### ISSUE THREAD

**Issue by Sega100500** [terser/terser#1236]
Ruby 3.1.2
Ruby on Rails 7.0.3.1
gem terser 1.1.2
gem execjs 2.8.1
Third party library: Bootstrap **5.2** ( [new version 5.2 released](https://blog.getbootstrap.com/2022/07/19/bootstrap-5-2-0/) )

`app/assets/config/manifest.js` :
```javascript
//= link_tree ../images
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css

//= link lib/bootstrap/5.2.0/js/bootstrap.bundle.min.js
//= link lib/bootstrap/5.2.0/js/bootstrap.min.js
//= link lib/bootstrap/5.2.0/css/bootstrap.min.css
```

in view stylesheets and javascripts of Bootstrap are attached via `stylesheet_link_tag` and `javascript_include_tag`

`config/environments/production.rb` :
```ruby
config.assets.compile = true
config.assets.js_compressor = :terser
```

`log/production.log` :
```log
I, [2022-08-05T17:25:52.467898 #32459]  INFO -- : [68d4fa45-8cc1-4917-8483-c15acf50a2ee] Started GET "/" for 127.0.0.1 at 2022-08-05 17:25:52 +0500
I, [2022-08-05T17:25:52.470808 #32459]  INFO -- : [68d4fa45-8cc1-4917-8483-c15acf50a2ee] Processing by ApplicationBaseController#index as HTML
I, [2022-08-05T17:25:52.478778 #32459]  INFO -- : [68d4fa45-8cc1-4917-8483-c15acf50a2ee]   Rendered application_base/index.html.erb within layouts/application (Duration: 0.8ms | Allocations: 318)
I, [2022-08-05T17:25:52.736585 #32459]  INFO -- : [68d4fa45-8cc1-4917-8483-c15acf50a2ee]   Rendered layout layouts/application.html.erb (Duration: 258.7ms | Allocations: 117170)
I, [2022-08-05T17:25:52.736977 #32459]  INFO -- : [68d4fa45-8cc1-4917-8483-c15acf50a2ee] Completed 500 Internal Server Error in 266ms (ActiveRecord: 0.4ms | Allocations: 119134)
F, [2022-08-05T17:25:52.737617 #32459] FATAL -- : [68d4fa45-8cc1-4917-8483-c15acf50a2ee]   
[68d4fa45-8cc1-4917-8483-c15acf50a2ee] ActionView::Template::Error (
/tmp/execjs20220805-32459-i4mdfpjs:443
r.split("")}function member(name,array){return array.includes(name)}class Defa
                                                                    ^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
):
[68d4fa45-8cc1-4917-8483-c15acf50a2ee]   
[68d4fa45-8cc1-4917-8483-c15acf50a2ee] (execjs):1
```

**Comment by fabiosantoscode** [comment]
Hello! It looks like you're running this in an old node.JS version that doesn't support `class`, as this is valid syntax.
