### ISSUE TITLE
ng build --dev heads to Error: Optimization error [main.fe9785e49a33b769.js]: SyntaxError: Unexpected token: punc ({)

### ISSUE THREAD

**Issue by AdamKundracik** [terser/terser#1316]
`Angular version: 14.2.0`

`node version" 16.14.0`

`typescript version: 4.8.4`

Hi everyone,
I'm fighting with weird problem. After running 

`ng build --dev --projet="project name"`

my app don't want to build

it throws me this error on multiple files 

`Error: Optimization error [libs_frontend_domains_admin_companies_profile_feature_src_index_ts.2db0213594e6cb91.js]: SyntaxError: Unexpected token: punc ({)
`
or
`Error: Optimization error [main.fe9785e49a33b769.js]: SyntaxError: Unexpected token: punc ({)
`

After trying to find error I found this error 

`Error: Optimization error [main.fe9785e49a33b769.js]: SyntaxError: Unexpected token: punc ({)
    at js_error (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:554:11)
    at croak (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:1278:9)
    at token_error (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:1286:9)
    at unexpected (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:1292:9)
    at as_property_name (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:3082:20)
    at concise_method_or_getset (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:2735:20)
    at class_ (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:2691:22)
    at statement (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:1466:24)
    at _embed_tokens_wrapper (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:1343:26)
    at block_ (/Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/terser@5.14.2/node_modules/terser/dist/bundle.min.js:2178:20)
    at /Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/@angular-devkit+build-angular@14.2.10_t4wyd7xvdi4piymolsbdpzpxnu/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-plugin.js:154:55
    at async Promise.all (index 43)
    at async /Users/adam/Desktop/work/meta_dev/respect/node_modules/.pnpm/@angular-devkit+build-angular@14.2.10_t4wyd7xvdi4piymolsbdpzpxnu/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-plugin.js:158:21
`

I'm not using terser directly in package.json , and I don't know which package would use it.

What can be an issue?

Thanks

**Comment by jivanf** [comment]
Angular uses Terser when you enable optimized builds [here](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts#L104-L110). I'm also having the same problem which, interestingly, only happens with ES2022, ES2020 works fine. A temporary workaround would be to downgrade to ES2020, but if you need to use ES2022, you can also disable script optimizations and enable everything else like this (inside your build configuration):
```json
"optimization": {
    "scripts": false,
    "styles": true,
    "fonts": true
}
```

**Comment by fabiosantoscode** [comment]
You're using a very old Terser version. This project is at 5.x now. 

Errors like that usually mean syntax issues, that is, either the syntax is invalid or too modern for Terser. ES2022 introduced the class static block which is formatted like `static { }`. So @jivanf's comment seems like a great hypothesis.

To upgrade Terser I'm guessing you can upgrade angular-cli, which now wants a 5.x version.

https://github.com/angular/angular-cli/blob/fbfbca59a4e1cb0ead2f8069ab6a9f678c8e03b7/package.json#L206
