### ISSUE TITLE
Stackoverflow when compress chain of if statement

### ISSUE THREAD

**Issue by Solo-steven** [terser/terser#1432]
**Bug report or Feature request?**
When the terser compresses  a chain of if statements into a ternary operator, if maybe excess maximum call stack, related buf happened in [webpack issue](https://github.com/webpack/webpack/issues/17548)

**Version (complete output of `terser -V` or specific git commit)**
`terser 5.19.3`

**Complete CLI command or `minify()` options used**
```js
const { minify } = require('terser');

function makeFunctionText(arg, body) {
    return `(${arg}) => {\n${body}\n}`;
}

let body = ``;

for(let i =1 ; i <=3000; i+=2) {
    body += `if ({"${i}":1, "${i+1}":1}[index]) return "${i}${i+1}";\n`;
}

const functionText = makeFunctionText("index", body);

minify(functionText);
```

**`terser` input**
a chain of if statements, as the above program generates function text.

**`terser` output or error**
```
/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5648
        return visitor._visit(this, function() {
                                            ^

RangeError: Maximum call stack size exceeded
    at AST_ObjectKeyVal.<anonymous> (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5648:45)
    at TreeWalker._visit (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:6717:21)
    at AST_ObjectKeyVal._walk (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5648:24)
    at AST_Object.<anonymous> (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5621:31)
    at TreeWalker._visit (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:6717:21)
    at AST_Object._walk (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5618:24)
    at AST_Sub.<anonymous> (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5394:29)
    at TreeWalker._visit (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:6717:21)
    at AST_Sub._walk (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5393:24)
    at AST_Conditional.<anonymous> (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5530:32)

Node.js v18.12.1
❯ node index.js
/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:15184
    var tw = new TreeWalker(function(node, descend) {
                                    ^

RangeError: Maximum call stack size exceeded
    at TreeWalker.visit (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:15184:37)
    at TreeWalker._visit (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:6713:24)
    at AST_ObjectKeyVal._walk (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5648:24)
    at AST_Object.<anonymous> (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5621:31)
    at TreeWalker._visit (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:6717:21)
    at AST_Object._walk (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5618:24)
    at AST_Sub.<anonymous> (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5394:29)
    at TreeWalker._visit (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:6717:21)
    at AST_Sub._walk (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5393:24)
    at AST_Conditional.<anonymous> (/Users/litingwei/Desktop/reproduce/terser-if-statement/node_modules/terser/dist/bundle.min.js:5530:32)
```

**Expected result**
terser can compress a chain of if statements without throwing a StackOverflow error.

**Comment by Solo-steven** [comment]
hi @fabiosantoscode  I am interested in solving this bug. could you help me find out where the compress logic is in those files? thanks ~

**Comment by fabiosantoscode** [comment]
Haha I go to ONE music festival and chrome is overflowing on nested ternaries

**Comment by fabiosantoscode** [comment]
@Solo-steven feel free to give it a shot! I think the link you posted isn't quite it, because the issue disappears when I disable the `conditionals` option.

**Comment by fabiosantoscode** [comment]
Found the chrome bug reports, for future reference:

 - https://bugs.chromium.org/p/v8/issues/detail?id=13887
 - https://bugs.chromium.org/p/v8/issues/detail?id=12155

**Comment by fabiosantoscode** [comment]
Sorry, I misread this issue as just a repost of the webpack one, but it's about Terser's own crash.

**Comment by Solo-steven** [comment]
Hi @fabiosantoscode thanks for your reply, I found that Terser would use loop to transform if statements into conditional expressions, the stackoverflow problem seems to happen when transforming conditional expression . As following console show : (when loop is `for(let i =1 ; i <=6; i+=2)`)
```
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before transform if
after transform if
before if opti
before transform condition
after transform condition
before transform condition
after transform condition
after if opti
before transform if
after transform if
before transform if
after transform if
before if opti
before transform condition
after transform condition
before transform condition
after transform condition
after if opti
before transform if
after transform if
before transform if
after transform if
before if opti
before transform condition
after transform condition
before transform condition
after transform condition
after if opti
before transform condition
before transform condition
before transform condition
after transform condition
after transform condition
after transform condition
before transform condition
before transform condition
before transform condition
after transform condition
after transform condition
after transform condition

before transform condition
before transform condition
before transform condition
after transform condition
after transform condition
after transform condition
```
I want to ask if you know that after opti if statement, where maybe the place that recursive transform conditional expressions happend ? thanks ~

**Comment by fabiosantoscode** [comment]
The compressor is a subclass of TreeTransformer, which is inherently recursive.

Here's [one example](https://github.com/terser/terser/blob/master/lib/transform.js#L262-L266) of it recursing (.transform(tw) will use the TreeTransformer to transform inside, which involves another call stack item or two).

Also, [often when returning a new node from an optimization](https://github.com/terser/terser/blob/master/lib/compress/index.js#L1112-L1113), which is very frequent, the compressor is run on that node (and its child nodes) to invoke further compression as necessary.
