### ISSUE TITLE
NPE in scan_ref_scoped method

### ISSUE THREAD

**Issue by paztis** [terser/terser#1457]
It seems there's a null pointer in scan_ref_scoped function lib/compress/drop-unused.js line 445
in this code:
```
if (sym instanceof AST_SymbolRef
            && !is_ref_of(node.left, AST_SymbolBlockDeclaration)
            && self.variables.get(sym.name) === (node_def = sym.definition())
        ) {
```

self.variables can be null.

This fix seems to resolve the compilation
```
if (sym instanceof AST_SymbolRef
            && !is_ref_of(node.left, AST_SymbolBlockDeclaration)
            && self.variables
            && self.variables.get(sym.name) === (node_def = sym.definition())
        ) {
```

**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser@5.21.0

**Complete CLI command or `minify()` options used**
default webpack@5.88.2 configuration

**`terser` input**

**`terser` output or error**
```
ERROR in digital-exp-b-2-b.js
digital-exp-b-2-b.js from Terser plugin
Cannot read properties of undefined (reading 'get')
TypeError: Cannot read properties of undefined (reading 'get')
    at scan_ref_scoped (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:15413:31)
    at TreeWalker.visit (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:15172:16)
    at TreeWalker._visit (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:6713:24)
    at AST_Assign._walk (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:5496:24)
    at AST_SimpleStatement.<anonymous> (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:3861:23)
    at TreeWalker._visit (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:6717:21)
    at AST_SimpleStatement._walk (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:3860:24)
    at walk_body (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:3872:17)
    at AST_ClassStaticBlock.<anonymous> (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:6002:13)
    at TreeWalker._visit (/Users/jeromeh/Workspaces/experience-core-lcep-support/generated-code-example/temporary-app/workspace/node_modules/terser/dist/bundle.min.js:6717:21)

webpack 5.88.2 compiled with 1 error in 37217 ms
```

**Expected result**
Correct minification

**Comment by fabiosantoscode** [comment]
I appreciate the report! Thanks for confirming that fix is sufficient. I'll also have to check around that area to see if and how some assumption is being ignored. "self.variables" should always exist given a scope object.

I'll have time to work on this tomorrow

**Comment by paztis** [comment]
Seems to be ok. Thanks
