### ISSUE TITLE
ERROR: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ajmeese7** [terser/terser#1477]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**
`terser 5.24.0`

**Complete CLI command or `minify()` options used**

```shell
terser temp_file --compress -o temp_file
```

**`terser` input**
[obfuscated_malware.zip](https://github.com/terser/terser/files/13468427/obfuscated_malware.zip)

As you can guess from the file name, I am trying to run `terser` on a heavily obfuscated malware sample as part of a deobfuscation pipeline that I am developing. Please **do not** run the sample on your local machine, as I am unsure exactly what the code does yet.

**`terser` output or error**

```shell
ERROR: Maximum call stack size exceeded
    at AST_Binary.clone (/home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:3788:20)
    at TreeTransformer.before (/home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:3782:33)
    at AST_Binary.transform (/home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:6860:41)
    at /home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:7013:27
    at AST_Binary.transform (/home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:6863:13)
    at AST_Binary._clone (/home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:3780:25)
    at AST_Binary.clone (/home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:3789:21)
    at TreeTransformer.before (/home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:3782:33)
    at AST_Binary.transform (/home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:6860:41)
    at /home/ajmeese7/.nvm/versions/node/v16.20.2/lib/node_modules/terser/dist/bundle.min.js:7013:27
```

**Expected result**
Unsure, but looking to automatically remove the unused code so I can pass it to `eslint` for linting.

This is similar to #728, but the code in question is obviously different, so I'm hoping this will have a better chance of the root issue being discovered and resolved.

**Comment by fabiosantoscode** [comment]
I looked into it and it seems like Terser ran out of stack space. Obfuscation must have made it aggressively deep, and Terser does use recursion, a fact that can't really change.

But you can work around this by changing node's maximum stack size.

`node --stack-size=2000 node_modules/.bin/terser {file} -c`, which allocates 2000kb for the stack, worked for this file.

**Comment by ajmeese7** [comment]
@fabiosantoscode thanks so much for your help and quick response! I'll give that a go, you're the bomb 🚀
