### ISSUE TITLE
Failure to compress on hexadecimal numbers

### ISSUE THREAD

**Issue by prcdpr** [terser/terser#1496]
**Bug report or Feature request?**

Bug report.

**Version (complete output of `terser -V` or specific git commit)**

terser 5.28.0

**Complete CLI command or `minify()` options used**

`terser.cmd "repro.js" --compress`

**`terser` input**

`repro.js`
```js
if (node == null || clockseq == null) {
  var seedBytes = options.random || (options.rng || rng)();

  if (node == null) {
    // Per 4.5, create and 48-bit node id, (47 random bits + multicast bit = 1)
    node = _nodeId = [
      seedBytes[0] | 0x01,
      seedBytes[1],
      seedBytes[2],
      seedBytes[3],
      seedBytes[4],
      seedBytes[5],
    ];
  }

  if (clockseq == null) {
    // Per 4.2.2, randomize (14 bit) clockseq
    clockseq = _clockseq = ((seedBytes[6] << 8) | seedBytes[7]) & 0x3fff;
  }
}
```

**`terser` output or error**

```
Trace: {
  node1: AST_Number {
    value: 16383,
    raw: '0x3fff',
    start: [AST_Token `16383` at 18:66],
    end: [AST_Token `16383` at 18:66],
    flags: 768
  },
  node2: undefined
}

ERROR: Cannot read properties of undefined (reading 'TYPE')
    at shallow_cmp (terser\dist\bundle.min.js:11256:33)
    at equivalent_to (terser\dist\bundle.min.js:11261:10)
    at AST_Number.equivalent_to (terser\dist\bundle.min.js:18775:12)
    at terser\dist\bundle.min.js:20983:45
    at AST_Binary.optimize (terser\dist\bundle.min.js:18736:19)
    at Compressor.before (terser\dist\bundle.min.js:18714:24)
    at AST_Binary.transform (terser\dist\bundle.min.js:6864:41)
    at terser\dist\bundle.min.js:7018:29
    at Compressor.before (terser\dist\bundle.min.js:18709:9)
    at AST_Assign.transform (terser\dist\bundle.min.js:6864:41)
```

**Expected result**

It should print minimized code.

**Comment by fabiosantoscode** [comment]
Thank you very much for this repro!

I've already reverted the whole release, so grab `5.28.1` and you'll be fine. In the meantime I'll work through this.
