### ISSUE TITLE
`ERROR: EBADF: bad file descriptor` when using pipes

### ISSUE THREAD

**Issue by gprossliner** [terser/terser#1567]
**Bug report or Feature request?**

I'd consider it a BUG

**Version (complete output of `terser -V` or specific git commit)**
npx terser -V
terser 5.36.0
tested on MacOS

**Complete CLI command or `minify()` options used**

This is run by a GitHub action. The piped command argument is supposed to print the current version to the console.
I tried this to avoid creating a temp file, which would work:

```
# ok
echo console.log\(\"CODE-VERSION\", \"$(git rev-parse --short HEAD)\"\) > version.js
npx terser version.js test.js --output ./dist/test.js --source-map

# nok
npx terser <(echo console.log\(\"CODE-VERSION\", \"$(git rev-parse --short HEAD)\"\)) test.js --output ./dist/test.js --source-map
ERROR: EBADF: bad file descriptor, open '/dev/fd/63'...
```

**`terser` input**

**`terser` output or error**
```
npx terser <(echo console.log\(\"CODE-VERSION\", \"$(git rev-parse --short HEAD)\"\)) test.js --output ./dist/test.js --source-map
ERROR: EBADF: bad file descriptor, open '/dev/fd/63'
    at Object.readFileSync (node:fs:457:20)
    at read_file (/Users/.../node_modules/terser/dist/bundle.min.js:32521:23)
    at /Users/.../node_modules/terser/dist/bundle.min.js:32327:41
    at Array.forEach (<anonymous>)
    at run_cli (/Users/.../node_modules/terser/dist/bundle.min.js:32326:32)
```

**Expected result**

Should be generated as is was a normal file. 

I tested if node.js itself has a problem with pipes, but it seem to work fine, even with using `readFileSync`, as this test worked:

```
# test.js
const fs=require('fs')
const file=process.argv[2]
console.log("using file ", file)
const content= fs.readFileSync(file, "utf-8")
console.log(content)

node test.js <(echo console.log\(\"CODE-VERSION\", \"$(git rev-parse --short HEAD)\"\))
using file  /dev/fd/63
console.log("CODE-VERSION", "297c4e3")
```

**Comment by fabiosantoscode** [comment]
I can't reproduce on linux, fyi. What shell are you using? I'm using bash here.

```
 ♥  npx terser <(cat terser.mjs) terser.mjs --output /tmp/xx
 ♥  npx terser <(cat terser.mjs) terser.mjs --output /tmp/xx --source-map
 ♥  cat /tmp/xx
#!/usr/bin/env node
"use strict";import"./too....
```
