### ISSUE TITLE
Parsing error with await operator

### ISSUE THREAD

**Issue by epikgit** [terser/terser#1572]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 5.36.0

**Complete CLI command or `minify()` options used**
terser dist/js/db.js

**`terser` input**
const db =  {};
db.fx = async function(){}
const fxRep = await db.fx();
export default db;

**`terser` output or error**
Parse error at dist/js/db.js:5,20
const fxRep = await db.fx();
                    ^
ERROR: Unexpected token: name (db)
    at js_error (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:536:11)
    at croak (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:1264:9)
    at token_error (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:1272:9)
    at unexpected (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:1278:9)
    at semicolon (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:1316:56)
    at statement (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:1520:17)
    at _embed_tokens_wrapper (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:1329:26)
    at parse_toplevel (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:3610:23)
    at parse (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:3623:7)
    at minify_sync_or_async (D:\Temp\Play\node_modules\terser\dist\bundle.min.js:31996:42)

**Expected result**
Not an error!
If I remove async/await from the source everything works as it should.

**Comment by Conduitry** [comment]
This works for me in the REPL - https://try.terser.org/ - Do you have something configured to use an older ES version that doesn't support top-level await?
