### ISSUE TITLE
False positive "Unexpected token: punc ([)" on multiple class properties

### ISSUE THREAD

**Issue by yume-chan** [terser/terser#1574]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

5.36.0

**Complete CLI command or `minify()` options used**

```sh
> terser input.js --compress
```

**`terser` input**

```js
new class {
  a
  ["b"]
}
```

**`terser` output or error**

```text
Parse error at input.js:3,2
  ["b"]
  ^
ERROR: Unexpected token: punc ([)
    at js_error (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:536:11)
    at croak (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:1264:9)
    at token_error (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:1272:9)
    at unexpected (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:1278:9)
    at class_ (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:2697:28)
    at statement (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:1456:24)
    at _embed_tokens_wrapper (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:1329:26)
    at parse_toplevel (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:3610:23)
    at parse (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:3623:7)
    at minify_sync_or_async (D:\dev\yume-chan\undici\node_modules\.pnpm\terser@5.36.0\node_modules\terser\dist\bundle.min.js:31996:42)
```

**Expected result**

Parse and minify the code. The code is valid and defines two properties (`a` and `b`):

```sh
> node -e $'console.log(new class {a\n["b"]})'
{ a: undefined, b: undefined }
```

**Comment by paztis** [comment]
Same for me: undici last version is not bundlable in webpack because of it

**Comment by fabiosantoscode** [comment]
Thank you for the report! I will look into it this afternoon

**Comment by fabiosantoscode** [comment]
This is caused by the "[" character. A workaround is to add a semicolon before the offending token, or, if your beautifier tool gets in the way, initialize it to undefined and add a semicolon. I'll release the fix tomorrow.

**Comment by paztis** [comment]
I see in the commit it supports now
class A {
            a
            ["b"]
        }

But did it support also dynamic names like below ?
class A {
            a
            [MyVar]
        }

Le mer. 4 déc. 2024, 19:32, Fábio Santos ***@***.***> a
écrit :

**Comment by fabiosantoscode** [comment]
Yes @paztis. This parser bug was caused by having a `[` without a preceding `;`

**Comment by paztis** [comment]
Perfect. Thanks

Le mer. 4 déc. 2024, 20:34, Fábio Santos ***@***.***> a
écrit :
