### ISSUE TITLE
Terser breaks on \u2028

### ISSUE THREAD

**Issue by astronomersiva** [terser/terser#218]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V`)**
3.14.0

**Complete CLI command or `minify()` options used**
`terser --compress -- input.js`

**`terser` input**

```
// Github doesn't let pasting the \u2028 character
let message = 'Hello ';
```

**`terser` output or error**
```
Parse error at input.js:1,14
let message = 'Hello ';
              ^
ERROR: Unterminated string constant
    at cn.get (/Users/siva/.nvm/versions/node/v10.14.2/lib/node_modules/terser/lib/utils.js:73:23)
    at fatal (/Users/siva/.nvm/versions/node/v10.14.2/lib/node_modules/terser/bin/uglifyjs:302:53)
    at run (/Users/siva/.nvm/versions/node/v10.14.2/lib/node_modules/terser/bin/uglifyjs:241:9)
    at Object.<anonymous> (/Users/siva/.nvm/versions/node/v10.14.2/lib/node_modules/terser/bin/uglifyjs:169:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**Expected result** Runs without an error

**Comment by avdg** [comment]
This is a multi byte character, so maybe an encoding issue? Terser should only support ucs-2, meaning that characters requiring more than 2 bytes should use the surrogates (which are 2 character sequences each being 2 bytes long).

Note that the parser doesn't support full utf-8 as the standard assumes ucs-2 and this being a very rare case that could be worked around in many ways (using ucs-2 or escaped string characters).

**Comment by avdg** [comment]
Seems there are some cases that break, but some cases that work correctly (still need to dig deeper myself):

scripts/u2028.js:
```js
const minify = require('../dist/bundle');

const u20208Escaped = 'Hello\u2028';
const u2028Utf8Buffer = Buffer.from('Hello\u2028', 'utf8');
const u2028Ucs2Buffer = Buffer.from('Hello\u2028', 'utf8');

console.log(u20208Escaped.split('').map(c=>c.charCodeAt(0).toString(16)));
console.log(minify.minify(u20208Escaped));

console.log(u2028Utf8Buffer.toString('utf8').split('').map(c=>c.charCodeAt(0).toString(16)));
console.log(minify.minify(u2028Utf8Buffer.toString('utf8')));

console.log(u2028Ucs2Buffer.toString('ucs2').split('').map(c=>c.charCodeAt(0).toString(16)));
console.log(minify.minify(u2028Ucs2Buffer.toString('ucs2')));
```

Running with node v10.15.3
```
terser> node .\scripts\u2028-test.js
[ '48', '65', '6c', '6c', '6f', '2028' ]
{ code: 'Hello;' }
[ '48', '65', '6c', '6c', '6f', '2028' ]
{ code: 'Hello;' }
[ '6548', '6c6c', 'e26f', 'a880' ]
{ error:
   { SyntaxError: Unexpected character ''
       at JS_Parse_Error.get (dist\bundle.js:79:25)
       at formatError (internal/util/inspect.js:817:16)
       at formatRaw (internal/util/inspect.js:625:16)
       at formatValue (internal/util/inspect.js:511:10)
       at formatProperty (internal/util/inspect.js:1070:11)
       at formatRaw (internal/util/inspect.js:726:11)
       at formatValue (internal/util/inspect.js:511:10)
       at inspect (internal/util/inspect.js:191:10)
       at Object.formatWithOptions (util.js:84:12)
       at Console.(anonymous function) (console.js:191:15)
     message: 'Unexpected character \'\'',
     filename: '0',
     line: 1,
     col: 2,
     pos: 2 } }
```

**Comment by fabiosantoscode** [comment]
Fixed when implementing this ES proposal: https://github.com/tc39/proposal-json-superset
