### ISSUE TITLE
Error destructuring keyword "async" with default value

### ISSUE THREAD

**Issue by jacktuck** [terser/terser#329]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V`)**
terser 3.17.0

**Complete CLI command or `minify()` options used**
terser test.js

**`terser` input**
```
// ok
const { async = true } = {};

// ok
({ _async = true }) => {};

// ok
({ async }) => {};

// error
({ async = true }) => {};
```
**`terser` output or error**
```
Parse error at test.js:11,9
({ async = true }) => {};
         ^
ERROR: Unexpected token: operator (=)
    at Z.get (/Users/Jack/.nvm/versions/node/v9.4.0/lib/node_modules/terser/lib/utils.js:83:23)
    at fatal (/Users/Jack/.nvm/versions/node/v9.4.0/lib/node_modules/terser/bin/uglifyjs:311:53)
    at run (/Users/Jack/.nvm/versions/node/v9.4.0/lib/node_modules/terser/bin/uglifyjs:250:9)
    at Object.<anonymous> (/Users/Jack/.nvm/versions/node/v9.4.0/lib/node_modules/terser/bin/uglifyjs:178:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
```

**Expected result**
No error

**Comment by fabiosantoscode** [comment]
Thanks for this parser bug report!
