### ISSUE TITLE
Call stack size exceeded for recursive function

### ISSUE THREAD

**Issue by juliancarrivick** [terser/terser#406]
**Bug report or Feature request?** Bug report

**Version (complete output of `terser -V` or specific git commit)** 4.1.2

**Complete CLI command or `minify()` options used**
terser --compress --toplevel

**`terser` input**
``` javascript
getDecimalGreaterThanHalfRecurse(Math.random());

function getDecimalGreaterThanHalfRecurse(num) {
  if (num > 0.5) {
    return num;
  }
  return getDecimalGreaterThanHalf();
  function getDecimalGreaterThanHalf() {
    const childTaskFetchPromises = [];
    [Math.random()].forEach(makeSureNumberIsHalf);
    return childTaskFetchPromises[0];
    function makeSureNumberIsHalf(numToTry) {
      childTaskFetchPromises.push(getDecimalGreaterThanHalfRecurse(numToTry));
    }
  }
}
```

**`terser` output or error**
Full file paths removed for ease of reading
```
ERROR: Maximum call stack size exceeded
    at AST_SymbolRef.transform (\node_modules\terser\dist\bundle.min.js:1:78550)
    at node_modules\terser\dist\bundle.min.js:1:78745
    at l (node_modules\terser\dist\bundle.min.js:1:833)
    at e (node_modules\terser\dist\bundle.min.js:1:1153)
    at t (node_modules\terser\dist\bundle.min.js:1:78720)
    at node_modules\terser\dist\bundle.min.js:1:80515
    at AST_Call.transform (node_modules\terser\dist\bundle.min.js:1:78630)
    at node_modules\terser\dist\bundle.min.js:1:78745
    at l (node_modules\terser\dist\bundle.min.js:1:833)
    at e (node_modules\terser\dist\bundle.min.js:1:1153)
undefined
```
**Expected result**
If I switch the function call to be after the function declaration, it works with the following output
``` javascript
!function getDecimalGreaterThanHalfRecurse(num){return num>.5?num:function(){const childTaskFetchPromises=[];return[Math.random()].forEach(function(numToTry){childTaskFetchPromises.push(getDecimalGreaterThanHalfRecurse(numToTry))}),childTaskFetchPromises[0]}()}(Math.random());
```

**Anything else relevant?**
- I initially filed this under angular/angular-cli#15057
- If you remove the what seems to be useless function call to getDecimalGreaterThanHalf() then terser succeeds
- If you replace the forEach with a map (which is the same functionally) then terser succeeds. i.e. replace the body of getDecimalGreaterThanHalf with
```
return [Math.random()].map(makeSureNumberIsHalf);

    function makeSureNumberIsHalf(numToTry: number) {
      return getDecimalGreaterThanHalfRecurse(numToTry);
    }
```

**Comment by fabiosantoscode** [comment]
Awesome stuff, thank you for this detailed report!

**Comment by fabiosantoscode** [comment]
I've narrowed this down a bit.

It's only happening when `unused`, `reduce_funcs`, `reduce_vars` and `sequences` are all true. If any of these is set to false, the error does not happen.

**Comment by fabiosantoscode** [comment]
It seems to be fixed for me, with 4.1.4. Can you check @juliancarrivick ?

**Comment by abirmingham** [comment]
I am having this issue as well. Using `terser@4.1.4`, `terser-webpack-plugin@1.4.1`, `webpack@4.28.3`, and `webpack-cli@3.2.1`.

Config looks like this:
```javascript
    module.exports.optimization = {
        minimizer: [
            new TerserPlugin({
                terserOptions: {
                    mangle: {
                        reserved: [
                            'angular',
                            '$',
                            'd3',
                            'require',
                            'exports',
                            'Rickshaw',
                            '$super',
                        ],
                    },
                },
            }),
            new OptimizeCSSAssetsPlugin({}),
        ],
    };
```

```
ERROR in htmlgui.06b2494fd8d5f42a171a.js from Terser
RangeError: Maximum call stack size exceeded
    at Array.push (<anonymous>)
    at En.push (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:75317)
    at AST_VarDef.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78171)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78344
    at l (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:895)
    at e (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:1215)
    at gn (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78319)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80136
    at AST_Var.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78344
    at l (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:895)
    at e (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:1215)
    at gn (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78319)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80431
    at AST_Function.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80492
    at AST_Call.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80629
    at AST_Dot.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80492
    at AST_Call.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80629
    at AST_Dot.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80492
    at AST_Call.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:79496
    at AST_Return.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78344
    at l (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:895)
    at e (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:1215)
    at gn (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78319)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80431
    at AST_Function.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:81002
    at AST_Assign.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78851
    at AST_SimpleStatement.transform (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78228)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78344
    at l (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:895)
    at e (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:1215)
    at gn (/data/depot-ui/node_modules/terser/dist/bundle.min.js:1:78319)
    at /data/depot-ui/node_modules/terser/dist/bundle.min.js:1:80431
Makefile:234: recipe for target 'run-webpack' failed
make[1]: *** [run-webpack] Error 2
make[1]: Leaving directory '/data/depot-ui'
Makefile:223: recipe for target 'build/production-build-finished.tmp' failed
make: *** [build/production-build-finished.tmp] Error 2
```

**Comment by yanivfranco** [comment]
Yes! Help!

**Comment by yanivfranco** [comment]
So..I'm not using terser...but still get the error when I try to buikd my server using webpack with -- mode = production. This is my webpack config:

`const path = require("path");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const webpack = require("webpack");

const outputDirectory = "dist";

let plugins = [new webpack.NamedModulesPlugin(), new CleanWebpackPlugin([path.join(outputDirectory)])];

const entry = ["babel-polyfill", "./src/server/index"];

module.exports = [
  {
    entry: entry,
    output: {
      path: path.join(__dirname, outputDirectory),
      filename: "server.js"
    },
    module: {
      rules: [
        {
          test: /\.(ts|js)$/,
          exclude: /node_modules/,
          use: ["babel-loader"]
        }
      ]
    },
    resolve: {
      extensions: ["*", ".js", ".ts"]
    },
    plugins: plugins,
    target: "node",
    node: {
      console: false,
      global: false,
      process: false,
      Buffer: false,
      __filename: false,
      __dirname: false
    }
  }
];`

And this is the error i get:
`    ERROR in server.js from Terser
    RangeError: Maximum call stack size exceeded
        at En.before (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:171880)
        at AST_Dot.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78197)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80629
        at AST_Dot.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:81344
        at AST_ObjectKeyVal.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
        at e (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:1215)
        at gn (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78319)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:81239
        at AST_Object.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
        at e (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:1215)
        at gn (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78319)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80512
        at AST_Call.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80411
        at AST_Arrow.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
        at e (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:1215)
        at gn (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78319)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80512
        at AST_Call.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78851
        at AST_SimpleStatement.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
        at e (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:1215)
        at gn (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78319)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80431
        at AST_Arrow.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
`

Any thoughts?

**Comment by yanivfranco** [comment]
So..I'm not using terser...but still get the error when I try to buildmy server using webpack with -- mode  production. This is my webpack config:
```
const path = require("path");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const webpack = require("webpack");

const outputDirectory = "dist";

let plugins = [new webpack.NamedModulesPlugin(), new CleanWebpackPlugin([path.join(outputDirectory)])];

const entry = ["babel-polyfill", "./src/server/index"];

module.exports = [
  {
    entry: entry,
    output: {
      path: path.join(__dirname, outputDirectory),
      filename: "server.js"
    },
    module: {
      rules: [
        {
          test: /\.(ts|js)$/,
          exclude: /node_modules/,
          use: ["babel-loader"]
        }
      ]
    },
    resolve: {
      extensions: ["*", ".js", ".ts"]
    },
    plugins: plugins,
    target: "node",
    node: {
      console: false,
      global: false,
      process: false,
      Buffer: false,
      __filename: false,
      __dirname: false
    }
  }
];
```


And this is the error i get:
```
 ERROR in server.js from Terser
    RangeError: Maximum call stack size exceeded
        at En.before (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:171880)
        at AST_Dot.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78197)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80629
        at AST_Dot.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:81344
        at AST_ObjectKeyVal.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
        at e (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:1215)
        at gn (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78319)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:81239
        at AST_Object.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
        at e (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:1215)
        at gn (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78319)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80512
        at AST_Call.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80411
        at AST_Arrow.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
        at e (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:1215)
        at gn (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78319)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80512
        at AST_Call.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78851
        at AST_SimpleStatement.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
        at e (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:1215)
        at gn (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78319)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:80431
        at AST_Arrow.transform (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78228)
        at /home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:78344
        at l (/home/yafranco/Weddinv/source/node_modules/terser/dist/bundle.min.js:1:895)
```

One more important thing is that the build passes on my local machine with Windows OS...but when I try to deploy on Ubuntu I get this error...
Any thoughts?

**Comment by fabiosantoscode** [comment]
I find it unlikely that the node stack size is different for windows and linux.

It might be a different node version altogether. Are you on the latest Terser version?

Can you try to isolate the problematic code? I can't guess what code your project contains :)

**Comment by stevenao** [comment]
same problem, but 4.1.2 works. What has changed between 4.1.2 and 4.1.3? There is a code sample provided that can be used to debug the code change in 4.1.3 that is causing it. 

FYI, 4.1.3, 4.1.4 and 4.2.0 all are giving errors.

**Comment by juliancarrivick** [comment]
@fabiosantoscode sorry, meant to get to this on Friday. I just tried on 4.1.4 and 4.2.0 and it's still not working for me.
I get a different stack trace now though (4.2.0)
```
ERROR: Maximum call stack size exceeded
    at hn.before (\node_modules\terser\lib\compress\index.js:4020:38)
    at AST_SymbolLambda.before [as transform] (\node_modules\terser\lib\transform.js:96:31)
    at transform (\node_modules\terser\lib\transform.js:208:42)
    at AST_Function.descend [as transform] (\node_modules\terser\lib\transform.js:99:13)
    at transform (\node_modules\terser\lib\transform.js:222:39)
    at AST_Call.descend [as transform] (\node_modules\terser\lib\transform.js:99:13)
    at transform (\node_modules\terser\lib\transform.js:112:21)
    at f (\node_modules\terser\lib\utils\index.js:86:23)
    at doit (\node_modules\terser\lib\utils\index.js:111:52)
    at MAP (\node_modules\terser\lib\transform.js:111:12)
```

**Comment by fabiosantoscode** [comment]
I've fixed a similar issue (#432) in 4.2.1, give it a try as it's probably the same bug. But without a reproduction I can't drill down into the issue and find the problem.

@juliancarrivick you have this issue with different code I suppose? I can't reproduce the issue with the code you have given me (plus the toplevel option), which is now part of the test suite and hasn't failed since the bug has been fixed.

**Comment by Martii** [comment]
@fabiosantoscode 

> I find it unlikely that the node stack size is different for windows and linux.

:+1:

Refs:
``` console
$ uname -a
Linux machine 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ node --v8-options
…
  --stack-size (default size of stack region v8 is allowed to use (in kBytes))
        type: int  default: 984
…
```

``` console
$ uname -a
MINGW64_NT-6.1-7601 WIN7HP 3.0.7-338.x86_64 2019-07-03 15:16 UTC x86_64 Msys

$ node --v8-options
…
  --stack-size (default size of stack region v8 is allowed to use (in kBytes))
        type: int  default: 984
…
```

**Comment by juliancarrivick** [comment]
@fabiosantoscode Bingo!
```
$ node_modules/terser/bin/uglifyjs --version
terser 4.2.1

$ node_modules/terser/bin/uglifyjs --compress --toplevel repo.js
!function getDecimalGreaterThanHalfRecurse(num){if(num>.5)return num;return function(){const childTaskFetchPromises=[];return[Math.random()].forEach(function(numToTry){childTaskFetchPromises.push(getDecimalGreaterThanHalfRecurse(numToTry))}),childTaskFetchPromises[0]}()}(Math.random());
```

I then retried 4.2.0 and it failed again, so looks like 4.2.1 fixes this :)
Cheers for that 🍻

**Comment by fabiosantoscode** [comment]
Perfect :)
