### ISSUE TITLE
`ERROR: c.has is not a function` when using unsafe compression on __defineSetter__ used as global

### ISSUE THREAD

**Issue by m4rw3r** [terser/terser#524]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

Both 4.4.0 and b66fd6b0e0390006890bf397d2e642df1a6ab6ab

**Complete CLI command or `minify()` options used**

```
terser test.js -c unsafe
````

**`terser` input**

```javascript
__defineSetter__.call(null, key, function () { /* empty */ });
```

**`terser` output or error**

```
ERROR: c.has is not a function
    at AST_Dot.thedef [as _eval] (terser-master/lib/compress/index.js:3029:72)
    at AST_Dot.evaluate (terser-master/lib/compress/index.js:2793:24)
    at flatten_object (terser-master/lib/compress/index.js:6940:20)
    at AST_Dot.OPTIMIZED [as optimize] (terser-master/lib/compress/index.js:444:28)
    at Qn.this [as before] (terser-master/lib/compress/index.js:415:42)
    at AST_Dot.transform (terser-master/lib/transform.js:94:20)
    at do_list (terser-master/lib/transform.js:214:21)
    at Qn.node [as before] (terser-master/lib/compress/index.js:416:13)
    at AST_Call.transform (terser-master/lib/transform.js:94:20)
    at body (terser-master/lib/transform.js:121:10)
```

**Expected result**

```javascript
__defineSetter__.call(null,key,(function(){}));
```

**Comment by fabiosantoscode** [comment]
Nice catch! Thanks for this report!

**Comment by fabiosantoscode** [comment]
This is a very cool bug, and a nice reminder of why we should use maps instead of objects. Internally Terser has found a property called __defineSetter__ within an object, and is happily trying to use it as if it was a set, but it's a function. Fix coming up soon.
