### ISSUE TITLE
Parse Error: BigInt with hexadecimal

### ISSUE THREAD

**Issue by odanado** [terser/terser#525]
**Bug report**

**Version**
terser 4.4.0

**Complete CLI command**
`$ terser example.js`

**`terser` input**
ref: https://github.com/odanado/terser-bigint-hexadecimal

```example.js
const a = 0xffn
console.log(a)
```

**`terser` output or error**
```
Parse error at example.js:1,10
const a = 0xffn
          ^
ERROR: Invalid or unexpected token
    at js_error (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:361:11)
    at parse_error (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:494:9)
    at read_num (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:534:13)
    at Object.input (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:885:40)
    at peek (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:1023:56)
    at next (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:1028:24)
    at vardefs (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:2031:28)
    at const_ (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:2065:27)
    at parser (/Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:1287:28)
    at /Users/odan/source/github.com/odanado/terser-bigint-hexadecimal/node_modules/terser/lib/parse.js:1101:26
```

**Expected result**
succeed parse.

**Comment by fabiosantoscode** [comment]
Thanks! I didn't know one could use hex in BigDecimals

**Comment by fabiosantoscode** [comment]
Octal and binary are allowed too, I'll add them in.

**Comment by L2jLiga** [comment]
@fabiosantoscode, this PR broke 1 test with scientific format: `1e6n` - is not correct big interger
![image](https://user-images.githubusercontent.com/11780854/69916629-cd920880-148f-11ea-9ce0-488314a5748c.png)

**Comment by paulmillr** [comment]
@fabiosantoscode this regressed in 4.6.12

**Comment by paulmillr** [comment]
Test case: `'let r = {beta: 0x7ae96a2b657c07106e64479eac3434e99cf0497512f58995c1396c28719501een}; console.log(r.beta);'`

**Comment by fabiosantoscode** [comment]
@paulmillr thank you very much for this report. Next time though do open a new issue!

It seems to be caused by the lowercase. The workaround is to use uppercase hex.

**Comment by paulmillr** [comment]
@fabiosantoscode thanks. Is there a possibility this will be fixed by terser?

**Comment by fabiosantoscode** [comment]
This is simple enough to be fixed by today or tomorrow. I have to tend to my job though :)

**Comment by fabiosantoscode** [comment]
@paulmillr fix is in master. Terser gets released when most of the world is in working hours.

**Comment by paulmillr** [comment]
awesome!
