### ISSUE TITLE
Object inlining compression not syntactically valid in 4.5.0

### ISSUE THREAD

**Issue by vetruvet** [terser/terser#545]
**Bug report or Feature request?**

bug

**Version (complete output of `terser -V` or specific git commit)**

4.5.0

Previous version (4.4.3) works fine

**Complete CLI command or `minify()` options used**

`npx terser@4.5.0 --compress -- test.js | node`

test.js:

```
const myObject = {
  myMethod(someArg) {
    const someMapping = {
      'a': 1,
      'b': 2,
    };

    return someMapping[someArg];
  }
}

console.log('a:', myObject.myMethod('a'));
console.log('b:', myObject.myMethod('b'));
```

**`terser` output or error**

```
const myObject={myMethod:someArg=>{a:1,b:2}[someArg]};console.log("a:",myObject.myMethod("a")),console.log("b:",myObject.myMethod("b"));
                                        ^

SyntaxError: Unexpected token :
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at evalScript (internal/bootstrap/node.js:720:27)
    at Socket.process.stdin.on (internal/bootstrap/node.js:391:9)
    at Socket.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Expected result**

```
a: 1
b: 2
```

**Comment by fabiosantoscode** [comment]
This is an unintended consequence of a refactor. I'll fix this right away.

**Comment by fabiosantoscode** [comment]
If this occurred in an open source project with unit tests, let me know which so I can add it to Terser's functional tests, in addition to the regression test.

**Comment by fabiosantoscode** [comment]
4.5.1 is now out, thank you very much for the report!

**Comment by vetruvet** [comment]
Thanks for the quick turnaround!
