### ISSUE TITLE
Support for keeping parentheses intact?

### ISSUE THREAD

**Issue by juj** [terser/terser#564]
Acorn.js has support to retain parentheses around expressions. E.g.

```js
var a = (1+2);
```
yields
```
{
 "type": "Program",
 "start": 0,
 "end": 15,
 "body": [
  {
   "type": "VariableDeclaration",
   "start": 0,
   "end": 14,
   "declarations": [
    {
     "type": "VariableDeclarator",
     "start": 4,
     "end": 13,
     "id": {
      "type": "Identifier",
      "start": 4,
      "end": 5,
      "name": "a"
     },
     "init": {
      "type": "ParenthesizedExpression",
      "start": 8,
      "end": 13,
      "expression": {
       "type": "BinaryExpression",
       "start": 9,
       "end": 12,
       "left": {
        "type": "Literal",
        "start": 9,
        "end": 10,
        "value": 1,
        "raw": "1"
       },
       "operator": "+",
       "right": {
        "type": "Literal",
        "start": 11,
        "end": 12,
        "value": 2,
        "raw": "2"
       }
      }
     }
    }
   ],
   "kind": "var"
  }
 ],
 "sourceType": "script"
}
```
with a `ParenthesizedExpression` node.

In Emscripten to implement a JS<->Wasm interop optimizer, we are using acorn to parse JavaScript:

```js
var ast = acorn.parse(input, ...);
```
https://github.com/emscripten-core/emscripten/blob/aaeed12b140946f524c35091dd5c3749e0bbdb83/tools/acorn-optimizer.js#L960

then use

```js
var terserAst = terser.AST_Node.from_mozilla_ast(ast);
```

https://github.com/emscripten-core/emscripten/blob/aaeed12b140946f524c35091dd5c3749e0bbdb83/tools/acorn-optimizer.js#L982

to convert the acorn parsed AST to terser, and then finally use

```js
terserAst.print_to_string
```
https://github.com/emscripten-core/emscripten/blob/aaeed12b140946f524c35091dd5c3749e0bbdb83/tools/acorn-optimizer.js#L988

to print out the processed/optimized JavaScript.

If acorn's [preserveParens: true](https://www.npmjs.com/package/acorn) option is used, 
these ParenthesizedExpression nodes are produced.

In Emscripten this JS<->Wasm optimizer is run before Closure compiler is run, so it is necessary to be able to preserve some detail in this source->AST->source transformation. One such important detail are [Closure "type casts"](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System#type-casts), which are expressions of form

```js
var castedType = /**@type{typeToCastTo}*/(someOtherType);
```

hence there is a need to be able to retain both comments and parentheses around expressions. Comments are resolvable with existing terser code, but parentheses seem to be unsupported, and `terser.AST_Node.from_mozilla_ast()` aborts if it sees an acorn's (nonstandard) `ParenthesizedExpression` node.

In https://github.com/emscripten-core/emscripten/pull/10393/files#diff-15dcd31a44d5bf978143dff119dbc047R509 I hacked in a support to terser to parse and preserve parentheses to suit Emscripten's needs.

Now I am wondering if this support would be something that terser could officially implement support for?

**Comment by fabiosantoscode** [comment]
Preserving parens is a weird thing for Terser to do.

Adding them would entail creating a new kind of node, and handling it throughout all the compression code we have. The parsing and output are not the issue in this case.

What terser can do, is preserve calls to identity functions that are defined outside of the code you are minifying, if that's a good enough workaround for you. They don't even have to exist if you post process them away using something like estraverse. Example:

PARENS(1 + a)
CLOSURETYPECAST('typeToCastTo', 1 + a)

As you can see above this can even help preserve parens.

I've given much thought to enabling this kind of annotation, for things such as marking a portion of the code as pure, or even macros. Comments and parentheses tend to be lost as they are passed along different tools, be it through estree or a string.

**Comment by juj** [comment]
> and handling it throughout all the compression code we have. The parsing and output are not the issue in this case. The parsing and output are not the issue in this case.

In our use case we do not use terser to minify/compress JS code, but just use it to print an AST that flows to it from acorn, like mentioned above. That is, the AST conversion from acorn and output to JS from terser are the only thing that our use case needed. I do not actually know the history of the optimizer well enough to know why this kind of "parse with acorn, convert to terser to print the AST" logic came about. @kripken would know? I suppose acorn was missing a feature to print an AST back to JS?

> What terser can do, is preserve calls to identity functions that are defined outside of the code you are minifying, if that's a good enough workaround for you.

Unfortunately that would be quite a workaround for our need, and would result in people needing to learn to write nonidiomatic Closure annotation JSDocs, plus that might result in having to convert and maintain duplicate copies of existing JS files for this convention.

>  Comments and parentheses tend to be lost as they are passed along different tools, be it through estree or a string.

Agreed. Unfortunately comments and parentheses were what Closure team went with, so that is what I have to work with as a result :/

**Comment by fabiosantoscode** [comment]
UglifyJS has an AST conversion tool because, if you already have an AST for some reason (maybe you used babel to convert code or some other compiler), you can pass it to Terser instead of incurring the cost of converting it to a string, just so Terser can parse it back.

I can't complain about Closure compiler because Terser/UglifyJS also use comments :) `/*#__PURE__*/`, `/*#__INLINE__*/` and more might come.

**Comment by juj** [comment]
Perhaps good to note explicitly: currently if one uses acorn to parse an AST, with acorn's option `preserveParens: true`, and then attempts to bring the resulting AST over to terser, i.e.
```js
var ast = acorn.parse(input, { preserveParens:true });
var terserAst = terser.AST_Node.from_mozilla_ast(ast);
```
it will result in a cryptic exception:
```js
E:\code\emsdk\emscripten\master\tools\node_modules\terser\terser.js:8281
        var ret = node != null ? MOZ_TO_ME[node.type](node) : null;
                                                     ^

TypeError: MOZ_TO_ME[node.type] is not a function
    at from_moz (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:8281:54)
    at Object.To_Moz_Unary (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:7719:26)
    at from_moz (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:8281:54)
    at Object.From_Moz_IfStatement [as IfStatement] (eval at map (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:8267:21), <anonymous>:7:12)
    at from_moz (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:8281:54)
    at Array.map (<anonymous>)
    at Object.From_Moz_BlockStatement [as BlockStatement] (eval at map (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:8267:21), <anonymous>:7:14)
    at from_moz (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:8281:54)
    at Object.FunctionExpression (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:7429:44)
    at from_moz (E:\code\emsdk\emscripten\master\tools\node_modules\[4mterser[24m\terser.js:8281:54)
```
If terser thinks that acorn's (nonstandard) `ParenthesizedExpression` nodes should not be supported, then it would be at least good to improve the error handling in this kind of case to be more explicit.

**Comment by fabiosantoscode** [comment]
Perhaps the error message should be improved, especially now that EStree
keeps having new node types and Terser doesn't support esnext features.

**Comment by kripken** [comment]
> "parse with acorn, convert to terser to print the AST" logic came about. @kripken would know? I suppose acorn was missing a feature to print an AST back to JS?

I think acorn doesn't provide JS printing capabilities - it's [just a parser](https://github.com/acornjs/acorn/tree/master/acorn)? Or perhaps I missed a way to print in its API. I remember I looked at a few options for emitting the AST to JS, and terser was best.

**Comment by fabiosantoscode** [comment]
escodegen will save you some memory relative to terser if you're only looking to print an AST.

There's probably more.

**Comment by fabiosantoscode** [comment]
This too. It's apparently made to work with acorn so it might support that nonstandard parentheses node.

 https://www.npmjs.com/package/astring
