### ISSUE TITLE
Error running terser - value.contains_this is not a function

### ISSUE THREAD

**Issue by Nitix** [terser/terser#593]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

terser 4.6.6

**Complete CLI command or `minify()` options used**

Angular CLI 9, prod mode. `ng build --prod` and targetting es2015
I tried with peer dependency of angular that ships the version 4.5.1 and tried the latest version but its the same result.

**`terser` input**

I don't really know, it's tersering my whole project so I don't know where the problem comes from.

**`terser` output or error**

```
TypeError: e.contains_this is not a function
    at nr (/myapp/node_modules/terser/dist/bundle.min.js:1:214600)
    at AST_Dot.flatten_object (/myapp/node_modules/terser/dist/bundle.min.js:1:222742)
    at /myapp/node_modules/terser/dist/bundle.min.js:1:223827
    at AST_Dot.optimize (/myapp/node_modules/terser/dist/bundle.min.js:1:125288)
    at ri.before (/myapp/node_modules/terser/dist/bundle.min.js:1:125067)
    at AST_Dot.transform (/myapp/node_modules/terser/dist/bundle.min.js:1:79953)
    at /myapp/node_modules/terser/dist/bundle.min.js:1:83257
    at ri.before (/myapp/node_modules/terser/dist/bundle.min.js:1:125039)
    at AST_ObjectKeyVal.transform (/myapp/node_modules/terser/dist/bundle.min.js:1:79953)
    at /myapp/node_modules/terser/dist/bundle.min.js:1:80115

```

My attempt to resolve the issue is to verify that the function exists before trying to call the method. It's in an if statement so it was okish. But I don't know, if it's the right solution. 
My application is working with the "fix" but I haven't tested all the app.

**Comment by Nitix** [comment]
Building my project without using a minified terser gives
```
TypeError: value.contains_this is not a function
    at safe_to_flatten (/myapp/node_modules/terser/dist/bundle.min.js:15073:21)
    at AST_Dot.flatten_object (/myapp/node_modules/terser/dist/bundle.min.js:15229:24)
    at /myapp/node_modules/terser/dist/bundle.min.js:15301:28
    at AST_Dot.optimize (/myapp/node_modules/terser/dist/bundle.min.js:8725:21)
    at Compressor.before (/myapp/node_modules/terser/dist/bundle.min.js:8710:26)
    at AST_Dot.transform (/myapp/node_modules/terser/dist/bundle.min.js:5007:43)
    at /myapp/node_modules/terser/dist/bundle.min.js:5184:47
    at Compressor.before (/myapp/node_modules/terser/dist/bundle.min.js:8705:11)
    at AST_ObjectKeyVal.transform (/myapp/node_modules/terser/dist/bundle.min.js:5007:43)
    at /myapp/node_modules/terser/dist/bundle.min.js:5023:23
```
Hope it's help.

**Comment by L2jLiga** [comment]
Hi there!
@Nitix can you check is it fails in #594?

**Comment by Nitix** [comment]
Hi,
Terser stopped failing with this PR. 👍

**Comment by fabiosantoscode** [comment]
Forgot to say thanks for the report, but I appreciate it :)
