### ISSUE TITLE
Support import.meta

### ISSUE THREAD

**Issue by antony** [terser/terser#761]
**Bug report or Feature request?**

Bug

terser does not appear to support `import.meta` syntax.

**Version (complete output of `terser -V` or specific git commit)**

terser 4.8.0

**Complete CLI command or `minify()` options used**

npx terser hello.js

**`terser` input**

```
import.meta.env = { "foo": "bar" }
```

**`terser` output or error**

```npx terser hello.js                                                                                  22:54:17 
npx: installed 5 in 1.337s
Parse error at hello.js:1,6
import.meta.env = { "foo": "bar" }
      ^
ERROR: Unexpected token: punc (.)
    at js_error (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:369:11)
    at croak (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:1065:9)
    at token_error (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:1073:9)
    at unexpected (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:1079:9)
    at import_ (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:2614:13)
    at parser (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:1174:28)
    at statement (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:1123:26)
    at /home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:3161:23
    at parse (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/parse.js:3155:12)
    at Object.gr [as minify] (/home/ant/.npm/_npx/317229/lib/node_modules/terser/lib/minify.js:164:42)
```

**Expected result**

A minified version of the input :)

**Comment by fabiosantoscode** [comment]
This is pretty old syntax :) let's add this!
