### ISSUE TITLE
5.2.0 - Modules - Error: "c" is redeclared

### ISSUE THREAD

**Issue by dtruffaut** [terser/terser#794]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

C:\Projects>npx terser --version
terser 5.2.0

**Complete CLI command or `minify()` options used**

```
C:\Projects\skeet\pwa>npx terser C:/Projects/a.mjs C:/Projects/b.mjs --compress --ecma 2020 --module
```

**`terser` input**

a.mjs
```
let c;
```

b.mjs
```
let c;
```

**`terser` output or error**

```
Parse error at C:/Projects/b.mjs:1,4
let c;
    ^
ERROR: "c" is redeclared
    at js_error (C:\Projects\node_modules\terser\lib\parse.js:371:11)
    at TreeWalker.visit (C:\Projects\node_modules\terser\lib\scope.js:329:17)
    at TreeWalker._visit (C:\Projects\node_modules\terser\lib\ast.js:1531:24)
    at AST_SymbolLet._walk (C:\Projects\node_modules\terser\lib\ast.js:120:24)
    at AST_VarDef.<anonymous> (C:\Projects\node_modules\terser\lib\ast.js:809:23)
    at TreeWalker._visit (C:\Projects\node_modules\terser\lib\ast.js:1535:21)
    at AST_VarDef._walk (C:\Projects\node_modules\terser\lib\ast.js:808:24)
    at AST_Let.<anonymous> (C:\Projects\node_modules\terser\lib\ast.js:779:32)
    at TreeWalker._visit (C:\Projects\node_modules\terser\lib\ast.js:1535:21)
    at AST_Let._walk (C:\Projects\node_modules\terser\lib\ast.js:776:24)
```

**Expected result**

No error.

The --module option is given to the command line.
a.mjs and b.mjs should be processed as distincts modules.
Rather than being global, c is a module-scoped variable, and is declared locally (like inside a function).
Therefore, c is *not* redeclared.

**Comment by fabiosantoscode** [comment]
Interesting.

As it currently stands, `--module` doesn't make terser aware of module scope for multiple files.

In fact, when Terser is called with multiple files, all that happens in the output is simple concatenation. That option isn't module aware or do any bundling.

**Comment by dtruffaut** [comment]
**Real usage**

My modules all start the same way:

```js
let started = 0;

export const start = async () => {
    return started++ || await init();
};
const init = async () => {
    // ... Do one-time stuff
};
```

I do this because a module can be called from multiple files, and I absolutely don't know which one will be the first to call the module. Think about PWA pages, each one calling a i18n module.  You don't know what will be the page on which user will land from Google, but each pages will call the module. Initialization should happen once. You should not re-initialize when user clicks to another page (because PWA means SPA), even if the new page calls the module.

Anyway, my modules all start the same way.
So they all have the _started variable_ declared on top of file.

How can I scope these modules, or tell terser they are modules ?
(even with bits of code if terser cannot handle this ?)

**Comment by fabiosantoscode** [comment]
It sounds like you really need a bundler like webpack or rollup to achieve this.

They are oftentimes hard to configure but help you load ESM code (almost) transparently into each page, and allow for common code to be shared among your pages.

Even if Terser were to deduplicate your `started` variable, it would not be able to deduplicate your exports (if all are called `start`). If you want to achieve both, and create a mega-module you can rename your exports and refactor your code into something like:

```
export const {modulename} = (() => {
let started = 0;

const start = async () => {
    return started++ || await init();
};

const init = async () => {
    // ... Do one-time stuff
};

return start
})
```

If you concatenate a bunch of these using Terser, you'll end up with a large module with lots of exports. Using `import *` will let you merge modules as you request them and create a registry of all available functions which you can call.

But at this point you're creating a bundler yourself. Webpack can already do much of what I'm describing.

**Comment by dtruffaut** [comment]
I tried @evanwallace 's esbuild:
```
npx esbuild -outdir="${dir}" --target=esnext --out-extension:.js=.mjs --minify "${files.join('" "').replace(/\\/g, '\\\\')}"
```
Modules are properly scoped with this tool.
Not sure how he is handling this case, but it worked for me.

**Comment by fabiosantoscode** [comment]
esbuild is incredible. I was going to implement a bundler integrated with Terser, and gave up because something that good was already in the works.

Rollup's ES2020 issues shouldn't take long to fix. I can't blame them, I only finished optional chaining support for Terser yesterday. It was really hard to get right, and the ESTree spec was late.
