### ISSUE TITLE
Parse optional chaining with property named "default" 

### ISSUE THREAD

**Issue by pioug** [terser/terser#796]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**

terser@5.2.0

**Complete CLI command or `minify()` options used**

```sh
npx terser --compress -- src.js
```

**`terser` input**

```js
const x = window.metadata?.default;
```

**`terser` output or error**

```
$ npx terser --compress -- src.js 
npx: installed 5 in 1.173s
Parse error at test.js:1,27
const x = window.metadata?.default;
                           ^
ERROR: Unexpected token: keyword (default)
    at js_error (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:371:11)
    at croak (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:1084:9)
    at token_error (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:1092:9)
    at unexpected (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:1098:9)
    at subscripts (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:3002:34)
    at subscripts (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:2930:20)
    at expr_atom (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:2321:20)
    at maybe_unary (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:3070:19)
    at expr_ops (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:3121:24)
    at maybe_conditional (/Users/piou/.npm/_npx/28813/lib/node_modules/terser/lib/parse.js:3126:20)
```

**Expected result**

I expect to not have any error. I think it's related to `default` being a reserved keyword? If I rename the property `default` it would work fine.

---

I just found out this particular case when minifying my project 💦  
Anyway, thank you for implementing this feature! It's one thing less to transpile for projects running on evergreen browsers ❤️

**Comment by fabiosantoscode** [comment]
Thank you for reporting this!

This is one of the intricacies of the parser. There's a condition where we check whether the previous token is a dot, to make the next token accept keywords as if they were names. I'm fixing this condition such that it also checks for a ?. since the rules are the same as a dot.
