### ISSUE TITLE
Function named `delete` treated as operator during optional chaining.

### ISSUE THREAD

**Issue by Kruithne** [terser/terser#814]
**Bug report or Feature request?**
Bug report.

The following snippet of code attempts to retrieve a value from a [Map<>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) using optional chaining. The expected value is a [Set<>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) which has the [delete](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/delete) function available. This is perfectly valid, however Terser throws an error (added below) indicating that it appears to be treating it as [the delete operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete) after the optional chaining, rather than a function call.

```javascript
const foo = new Map();
foo.set('bar', new Set());
foo.get('bar')?.delete(5);
```

**Version (complete output of `terser -V` or specific git commit)**
5.2.0

**`terser` input**
```javascript
const terser = require("terser");
await terser.minify("const foo = new Map(); foo.set('bar', new Set()); foo.get('bar')?.delete(5);");
```

**`terser` output or error**
```
SyntaxError: Unexpected token: operator (delete)
    at js_error (C:\src\node_modules\terser\dist\bundle.min.js:538:11)
    at croak (C:\src\node_modules\terser\dist\bundle.min.js:1251:9)
    at unexpected (C:\src\node_modules\terser\dist\bundle.min.js:1265:9)
    at subscripts (C:\src\node_modules\terser\dist\bundle.min.js:3169:34)
    at subscripts (C:\src\node_modules\terser\dist\bundle.min.js:3127:20)
    at subscripts (C:\src\node_modules\terser\dist\bundle.min.js:3097:20)
    at subscripts (C:\src\node_modules\terser\dist\bundle.min.js:3097:20)
    at expr_atom (C:\src\node_modules\terser\dist\bundle.min.js:2488:20)
    at maybe_unary (C:\src\node_modules\terser\dist\bundle.min.js:3237:19)```

**Comment by Kruithne** [comment]
Resolved in c70f4b172ee98be229a5dc7f2346d02fbae9729f, thank you!
