### ISSUE TITLE
Crash on optional chaining optimization: ERROR: did not find a shallow_cmp function for AST_Chain

### ISSUE THREAD

**Issue by cbxp** [terser/terser#816]
**Bug report**

**Version 5.3.0**

**Complete CLI command or `minify()` options used**
`terser -c`

**`terser` input**

`if (project?.createdBy !== projectOwner?._id) loadProjectOwner()`

**`terser` output or error**

```
ERROR: did not find a shallow_cmp function for AST_Chain
    at AST_Chain.AST_Node.shallow_cmp (node_modules/terser/lib/equivalent-to.js:119:11)
    at shallow_cmp (node_modules/terser/lib/equivalent-to.js:68:47)
    at equivalent_to (node_modules/terser/lib/equivalent-to.js:73:10)
    at AST_Chain.equivalent_to (node_modules/terser/lib/compress/index.js:480:12)
    at node_modules/terser/lib/compress/index.js:5874:23
    at AST_Binary.optimize (node_modules/terser/lib/compress/index.js:452:19)
    at Compressor.before (node_modules/terser/lib/compress/index.js:437:24)
    at AST_Binary.transform (node_modules/terser/lib/transform.js:97:41)
    at node_modules/terser/lib/transform.js:169:37
    at Compressor.before (node_modules/terser/lib/compress/index.js:432:9)
```

**Expected result**
The same as input

**Comment by cbxp** [comment]
Probably related to #806

**Comment by MrPollux** [comment]
terser -c drop_console generates no error.

**Comment by fabiosantoscode** [comment]
I've fixed this and will do a release tomorrow!
