### ISSUE TITLE
No valid exports main found for terser

### ISSUE THREAD

**Issue by sabloger** [terser/terser#819]
After I update the Angular/cli and core to version 10, I am getting this error on `ng serve`:

```
An unhandled exception occurred: No valid exports main found for '.../node_modules/terser'
```

Can anyone help me please?

**Comment by sabloger** [comment]
the full error log:

```
[error] Error: No valid exports main found for '.../node_modules/terser'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (.../node_modules/terser-webpack-plugin/dist/minify.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (.../node_modules/terser-webpack-plugin/dist/index.js:32:15)
```

**Comment by TrySound** [comment]
Hey. Please upgrade your node. Node v13 is end of life and has buggy es modules support.

**Comment by fabiosantoscode** [comment]
Yes. I'm very curious as to whether this is still a problem on node 10, 12 or 14. I usually focus on supporting LTS versions.

**Comment by TrySound** [comment]
All "No valid exports main found" bugs I saw in many projects came from old node 13 users.

**Comment by msinghm** [comment]
**getting same issue**

on ng serve -o

_An unhandled exception occurred: No valid exports main found for '---\node_modules\terser'
See "---\angular-errors.log" for further details._
Versions:
NPM:6.13.1, Angular CLI: 8.3.19
Node: 13.3.0
OS: win32 x64
Angular: 10.1.2
@angular-devkit/architect         0.1001.2
@angular-devkit/build-angular     0.1001.2
@angular-devkit/build-optimizer   0.1001.2
@angular-devkit/build-webpack     0.1001.2
@angular-devkit/core              10.1.2
@angular-devkit/schematics        10.1.2
@ngtools/webpack                  10.1.2
@schematics/angular               10.1.2
@schematics/update                0.1001.2
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.44.1

Error log:
[error] Error: No valid exports main found for 'F:\workspace\Project\sales\ui\sales-app\node_modules\terser'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\workspace\Project\sales\ui\sales-app\node_modules\terser-webpack-plugin\dist\minify.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\workspace\Project\sales\ui\sales-app\node_modules\terser-webpack-plugin\dist\index.js:32:15)

**Comment by TrySound** [comment]
@msinghm Same answer. Upgrade node please.

**Comment by msinghm** [comment]
> @msinghm Same answer. Upgrade node please. You use buggy version.

upgraded node version to v14.11.0 and same app is working fine,

thanks so much for your help.

**Comment by fabiosantoscode** [comment]
I'm keeping this open until I have node 13 excluded in the package.json engines field.

**Comment by mitchelbower1** [comment]
Apologies for the noob question, but how would i go about updating node? can i do it through cli? or is it a manual download?

**Comment by fabiosantoscode** [comment]
If you're not familiar with tools such as nvm you can download the new node version and install it.
