### ISSUE TITLE
Minifying TypeScript

### ISSUE THREAD

**Issue by ajayjain** [terser/terser#840]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 4.8.0

**Complete CLI command or `minify()` options used**
{
    compress: true,
}

**`terser` input**

```
var Terser = require("terser");
var options = {
    compress: true,
};
var js_src = `declare let global;`
var output = Terser.minify(js_src, options);
console.log(output);
```

**`terser` output or error**

```
{
  error: Q [SyntaxError]: Unexpected token: keyword (let)
      at ee (/home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:19541)
      at c (/home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:28244)
      at l (/home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:28335)
      at f (/home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:28388)
      at g (/home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:28869)
      at T (/home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:34147)
      at /home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:30509
      at /home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:28976
      at /home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:50966
      at ce (/home/ajay/contracode/node_modules/terser/dist/bundle.min.js:1:51103) {
    filename: '0',
    line: 1,
    col: 8,
    pos: 8
  }
}
```

**Expected result**
While it doesn't make much sense to minify the definition `declare let global;`, I'd like to use Terser to transform (eg. remove dead code from) more realistic TypeScript programs. It seems to return a SyntaxError on every TypeScript program I've tried. Is there an option or a parser that supports TypeScript?

**Comment by fabiosantoscode** [comment]
Terser uses its own parser so it would be a big undertaking to support typescript as it evolves, and it wouldn't benefit minification that much.

Usually your programs would go through tsc before they get to Terser. This enables it to support any compile-to-js language without maintenance burden.
