### ISSUE TITLE
crash when hoist_vars a AST_Destructuring

### ISSUE THREAD

**Issue by gdh1995** [terser/terser#842]
**Bug report or Feature request?** bug report

**Version (complete output of `terser -V` or specific git commit)** 5.3.3 (also on 4.8.0)

**Complete CLI command or `minify()` options used** `./node_modules/terser/bin/terser -c hoist_vars a.js`

**`terser` input**

``` javascript
(()=>{
var d=1
console.log(3, d)
var {a, b} = {a: 1, b:2}
console.log(a, b)
})()
```

**`terser` output or error**

```
ERROR: def.name.definition is not a function
    at .\node_modules\terser\lib\compress\index.js:4992:24
    at Array.reduce (<anonymous>)
    at AST_Var.to_assignments (.\node_modules\terser\lib\compress\index.js:4972:40)
    at TreeTransformer.before (.\node_modules\terser\lib\compress\index.js:4149:40)
    at AST_Var.transform (.\node_modules\terser\lib\transform.js:97:41)
    at .\node_modules\terser\lib\transform.js:113:21
    at doit (.\node_modules\terser\lib\utils\index.js:104:23)
    at MAP (.\node_modules\terser\lib\utils\index.js:129:52)
    at do_list (.\node_modules\terser\lib\transform.js:112:12)
    at .\node_modules\terser\lib\transform.js:214:21
```

**Expected result**

something like:

``` javascript
(()=>{var d=1,{a,b}={a:1,b:2};console.log(3, d),console.log(a,b)})()
```

**Comment by fabiosantoscode** [comment]
Confirmed. Thanks for reporting!

**Comment by fabiosantoscode** [comment]
Fixed in https://github.com/terser/terser/commit/a626f5a162f95625f9b0d38fd9689efa7547ef5c
