### ISSUE TITLE
Error when running test using node.js 10.x or 12.x

### ISSUE THREAD

**Issue by learning** [terser/terser#875]
Follow the [`engines` of package.json](https://github.com/terser/terser/blob/master/package.json#L9)
```
"engines": {
  "node": ">=10"
}
```

Error occurs when running test on this project, using `10.15.3` or `12.4.0`

```
$ npm run test

> terser@5.4.0 test /Users/Learning/Documents/Playgrounds/terser
> node test/compress.js && mocha test/mocha

/Users/Learning/Documents/Playgrounds/terser/test/compress.js:2
import "source-map-support/register.js";
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terser@5.4.0 test: `node test/compress.js && mocha test/mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terser@5.4.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Learning/.npm/_logs/2020-11-18T03_16_21_718Z-debug.log
```

Everyting works well on `14.8.0`

**Comment by fabiosantoscode** [comment]
Hey there!

Terser is usually developed using more modern node releases, so since it's been distributed with ES modules, development with node 10 wasn't much of a concern. To run the Terser tests in node 10 you need to use [esm](https://www.npmjs.com/esm) like you can find in the .travis.yml file:

```
        node --require esm test/compress.js
        npm run test:mocha -- --require esm
```

**Comment by fabiosantoscode** [comment]
What the `engines` field means is that you can `npm install terser`, `require('terser')`, and use it in node 10.

Running the tests doesn't apply in my opinion.
