### ISSUE TITLE
Crashed when compress "not-initialized-variable" + template string inside function

### ISSUE THREAD

**Issue by mduclehcm** [terser/terser#876]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V` or specific git commit)**
terser **5.4.0**

**Complete CLI command or `minify()` options used**
```
terser test.js --compress
```

**`terser` input**
```js
// test.js
() => {
  let x;
  console.log(x + `?ts=${Date.now()}`);
};
```

**`terser` output or error**
```
ERROR: Cannot read property 'toString' of undefined
    at node_modules\terser\lib\compress\index.js:6257:45   
    at AST_Binary.optimize (node_modules\terser\lib\compress\index.js:452:19)
    at Compressor.before (node_modules\terser\lib\compress\index.js:437:24)
    at AST_Binary.transform (node_modules\terser\lib\transform.js:98:41)
    at node_modules\terser\lib\transform.js:114:21
    at doit (node_modules\terser\lib\utils\index.js:104:23)
    at MAP (node_modules\terser\lib\utils\index.js:129:52) 
    at do_list (node_modules\terser\lib\transform.js:113:12)
    at node_modules\terser\lib\transform.js:221:17
    at Compressor.before (node_modules\terser\lib\compress\index.js:432:9)
```
**Expected result**
Compress success without crash

**Isssue**
```js
 if (self.right instanceof AST_TemplateString) {
    var r = self.right;
    var l = self.left.evaluate(compressor); // l is undefined
    if (l != self.left) {
        r.segments[0].value = l.toString() + r.segments[0].value ;
        return r;
    }
}
```

**Comment by fabiosantoscode** [comment]
This is pretty serious!

Thanks for reporting, I'll have a look soon
