### ISSUE TITLE
Hash names cannot be compiled.

### ISSUE THREAD

**Issue by T3Lakuna** [terser/terser#897]
**Description**
This is a feature request for support of the stage 3 proposal defined on GitHub [here](https://github.com/tc39/proposal-private-methods) and described in the MDN Web Docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields).

**Bug report or Feature request?**
Feature request.

**Version (complete output of `terser -V` or specific git commit)**
`terser 5.5.1`

**Complete CLI command or `minify()` options used**
N/A

**`terser` input**

```js
class Foo {
	static publicStatic = "Public Static";
	static #privateStatic = "Private Static";
	#private;

	constructor() {
		this.public = "Public";
		this.#private = "Private";
	}

	bar() {
		console.log(Foo.#privateStatic); // "Private Static"
		console.log(this.#private); // "Private"
	}
}

const example = new Foo();

console.log(Foo.publicStatic); // "Public Static"
console.log(example.public); // "Public"

example.bar();
```

**`terser` output or error**

```sh
Parse error at C:\Users\tjmar\Desktop\test.js:3,8
        static #privateStatic = "Private Static";
               ^
ERROR: Unexpected character '#'
    at js_error (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:546:11)
    at parse_error (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:682:9)
    at Object.next_token [as input] (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1109:9)
    at peek (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1244:56)
    at next (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1249:24)
    at as_property_name (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:3033:13)
    at class_ (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:2664:47)
    at statement (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1445:24)
    at _embed_tokens_wrapper (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1322:26)
    at parse_toplevel (C:\Users\tjmar\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:3439:23)
```

**Expected result**

```js
class Foo{static publicStatic="Public Static";static #a="Private Static";#b;constructor(){this.public="Public";this.#b="Private"}bar(){console.log(Foo.#a);console.log(this.#b)}}const example=new Foo;console.log(Foo.publicStatic);console.log(example.public);example.bar();
```

**Comment by T3Lakuna** [comment]
The examples have been updated to be more inclusive in terms of static versus instance properties.

**Comment by tchetwin** [comment]
There are a couple of Issues tracking this:

- Original: [(#349) Feature Request: ES2018 private class field support](https://github.com/terser/terser/issues/349)
- More recent: [(#702) ERROR: Unexpected character '#' – private class fields](https://github.com/terser/terser/issues/702)
- Pull Request: [(#780) feat: support private class fields](https://github.com/terser/terser/pull/780)

**Comment by T3Lakuna** [comment]
Thank you for your response. I'm sorry, I didn't see these when I (poorly) searched for existing duplicate issues. Should I close this issue since it's a duplicate?

**Comment by T3Lakuna** [comment]
Closing this issue in favor of #702.
