### ISSUE TITLE
Error when export default anonymous class with extends

### ISSUE THREAD

**Issue by fffx** [terser/terser#924]
**Bug report**

**Version 5.5.1**

**Complete CLI command or `minify()` options used**
```
echo "export default class extends String {  }" | terser 
```

**`terser` input**
```
export default class extends String {  }
```

**`terser` output or error**
```
Parse error at 0:1,22
export default class extends String {  }
                      ^
ERROR: Unexpected token: keyword (extends)
    at js_error (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:546:11)
    at croak (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:1264:9)
    at token_error (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:1272:9)
    at unexpected (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:1278:9)
    at class_ (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:2651:13)
    at statement (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:1445:24)
    at _embed_tokens_wrapper (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:1322:26)
    at export_ (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:2989:28)
    at statement (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:1525:32)
    at _embed_tokens_wrapper (/Users/felix/.config/yarn/global/node_modules/terser/dist/bundle.min.js:1322:26)
```

**Expected result**

```
export default class extends String {}
```

**Comment by AxelTheGerman** [comment]
Was just about to log the same issue. I'm using the ruby wrapper [ahorek/terser-ruby](https://github.com/ahorek/terser-ruby) and one of the JS dependencies I'm using also exports default anonymous classes.

Any idea how easy this is to fix? It's been a while since I graduated but I hope this shouldn't be too much effort for someone who knows what they're doing

**Comment by fffx** [comment]
@AxelTheGerman  You can specify a class name

```
export default class FooString extends String {}
```

**Comment by AxelTheGerman** [comment]
@fffx thanks for jumping in. Yes adding a class name fixes the error. For now that workaround is good enough.

Going forward I was hoping I can directly import the ESM module of that library I'm using and then I need to either get the maintainers of that library to add a class name (as it shouldn't break anything on their side) or terser to be able to parse it 🙂

**Comment by fabiosantoscode** [comment]
Thanks for reporting this :muscle: pushed a fix just now
