### ISSUE TITLE
Terser fails to compress/mangle vanilla JS function if --module flag is enabled and possible reserved keyword error.

### ISSUE THREAD

**Issue by MenachemICTBIT** [terser/terser#944]
**Version 5.6.0

**Complete CLI command or `minify()` options used**

`terser "file" --output "./minifiedResultDir/newFilename" --compress drop_console=true --mangle --module`
**`terser` input**
```
function verifyPolicy (ipaddr, headers, pckg, port="443")
{
    var baseUrl = "https://" + ipaddr + ":" + port + "/";
    var fullUrl = baseUrl + "web_api/verify-policy";
    var data = {
        "policy-package" : pckg
    }
    var returnStatus = axios.post(fullUrl, data, headers).then((res) => {
        return { code : res.status, task : res.data };
    })
    .catch(err => {
        throw { code: err.response, message: err.response.data };
        })
    return returnStatus;
}
```
**`terser` output or error**
```
Parse error at ./myDirectory/myFileName.js:329,40
function verifyPolicy (ipaddr, headers, package, port="443")      
                                        ^
ERROR: Unexpected token: name (package)
    at js_error (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:548:11)
    at croak (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1272:9)
    at token_error (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1280:9)
    at unexpected (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1286:9)
    at Object.add_parameter (C:\Users\Menl\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1764:33)
    at binding_element (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:2021:29)
    at parameter (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1828:17)
    at parameters (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1802:25)
    at _function_body (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:2075:19)
    at function_ (C:\Users\AppData\Roaming\npm\node_modules\terser\dist\bundle.min.js:1726:20)
```

**Expected result**

No error.

**Comments**

Changing the variable name `package` to `pckg` overcame this error. Is `package` a reserved keyword? 
Edit: I am now also getting this same error for another, similar, function while using the parameter `static`. Changing the param name to `staticMember` (randomly chosen) fixed the issue. This is weird.

Anyway, I tried running this function inside the Terser REPL `https://try.terser.org/` and it just doesn't even recognize it at all, unless I remove the `module: true` option from the REPL options object; then it works fine. 

It seems to me that this is caused because my function is a non ES6 function, while I'm telling Terser to handle ES6 code. Most of my codebase is ES6 but we have some legacy JS from before that is getting messed up due to this error.

Any help is appreciated. Thank you.

**Comment by fabiosantoscode** [comment]
Hey there!

This is caused by the fact that "package" (as well as "static") is a reserved name in strict mode, as per the spec: https://262.ecma-international.org/11.0/#sec-keywords-and-reserved-words

> Those that are contextually disallowed as identifiers, in strict mode code: let, static, implements, interface, package, private, protected, and public;

Passing `--module` assumes strict mode, because ES6 modules have strict mode turned on by default, as if someone typed `"use strict"` on the first line.

If you use `--toplevel` instead of `--module`, you're using sloppy (non-strict) mode, and the words you're talking about will be able to be used as names.

**Comment by MenachemICTBIT** [comment]
Thanks for the response.  Thanks for verifying.
