### ISSUE TITLE
Unexpected token: punc (:) [Webpack error]

### ISSUE THREAD

**Issue by BustosAndrew** [terser/terser#967]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V` or specific git commit)**
5.6.1
**Complete CLI command or `minify()` options used**
gulp build

**`terser` output or error**
```
[18:29:53] Using gulpfile ~/Documents/GitHub/Box/Integration/gulpfile.js
[18:29:53] Starting 'build'...
[18:29:53] Starting 'webpack'...
[18:29:53] Starting 'webpack:client'...
[18:29:53] Starting 'webpack:server'...
[18:30:04] Finished 'webpack:server' after 10 s
[18:30:39] export 'default' (imported as 'tabbable') was not found in 'tabbable' (possible exports: focusable, isFocusable, isTabbable, tabbable)
[18:30:39] export 'default' (imported as 'tabbable') was not found in 'tabbable' (possible exports: focusable, isFocusable, isTabbable, tabbable)
[18:30:39] export 'default' (imported as 'tabbable') was not found in 'tabbable' (possible exports: focusable, isFocusable, isTabbable, tabbable)
[18:30:39] [Webpack errors]:
[18:30:39] activity-sidebar.js from Terser
Unexpected token: punc (:) [webpack://./node_modules/setimmediate/setImmediate.js:80,12][activity-sidebar.js:31047,18]
    at js_error (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1288:9)
    at semicolon (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1326:56)
    at simple_statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1583:73)
    at statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1369:47)
    at _embed_tokens_wrapper (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1339:26)
    at block_ (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:2172:20)
    at statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1403:29)
[18:30:39] 'webpack:client' errored after 45 s
[18:30:39] Error in plugin "webpack"
Message:
    1 webpack error(s) found.
[18:30:39] 'webpack' errored after 45 s
[18:30:39] 'build' errored after 45 s
```
**Expected result**
Should run the gulp build file just fine! To reproduce, install this npm package called box-ui-elements. Unfortunately, you also have to install all of its peer dependencies manually, or you can force install it, and continuously run npm audit fix --force inside the box-ui-elements node module package to get my terser error.

**Comment by Lornz-** [comment]
I got the exact same issue. Any suggestions on that one?

**Comment by BustosAndrew** [comment]
It was because I was using an npm package that required different build procedures. I was forced to include it as an html script tag.

**Comment by fabiosantoscode** [comment]
Hello @BustosAndrew! Could you please disable minification for this project and provide the output?

I've tried minifying this setimmediate module, but it works fine.

**Comment by jridgewell** [comment]
Closing as not reproducable.
